version: "2"
linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - gocritic
    - testifylint
  settings:
    gosec:
      excludes:
        - G117
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
    gofmt:
      rewrite-rules:
        - pattern: "interface{}"
          replacement: "any"
        - pattern: "a[b:len(a)]"
          replacement: "a[b:]"
    testifylint:
      disable-all: true
      enable:
        - require-error
        - useless-assert
        - len
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

