// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package buildkite

// BuildTest defines model for BuildTest.
type BuildTest struct {
	// Executions Present only when `include=executions`.
	Executions      []BuildTestExecution `json:"executions,omitempty"`
	ExecutionsCount int                  `json:"executions_count,omitempty"`

	// ExecutionsCountByResult Execution counts by result. `passed` and `failed` are always present;
	// `skipped`, `pending`, and `unknown` appear only when non-zero.
	ExecutionsCountByResult BuildTestExecutionsCount `json:"executions_count_by_result,omitempty"`
	ID                      string                   `json:"id,omitempty"`
	Labels                  []TestLabel              `json:"labels,omitempty"`
	LatestFail              *BuildTestLatestFail     `json:"latest_fail,omitempty"`
	Location                string                   `json:"location,omitempty"`
	Name                    string                   `json:"name,omitempty"`
	Reliability             float64                  `json:"reliability,omitempty"`
	Scope                   string                   `json:"scope,omitempty"`

	// State Test state.
	State string `json:"state,omitempty"`
}

// BuildTestExecution defines model for BuildTestExecution.
type BuildTestExecution struct {
	Duration        float64           `json:"duration,omitempty"`
	FailureExpanded []FailureExpanded `json:"failure_expanded,omitempty"`
	FailureReason   string            `json:"failure_reason,omitempty"`
	ID              string            `json:"id,omitempty"`
	Location        string            `json:"location,omitempty"`
	Status          string            `json:"status,omitempty"`
	Timestamp       *Timestamp        `json:"timestamp,omitempty"`
}

// BuildTestLatestFail defines model for BuildTestLatestFail.
type BuildTestLatestFail struct {
	Duration        float64           `json:"duration,omitempty"`
	FailureExpanded []FailureExpanded `json:"failure_expanded,omitempty"`
	FailureReason   string            `json:"failure_reason,omitempty"`
	ID              string            `json:"id,omitempty"`
	Timestamp       *Timestamp        `json:"timestamp,omitempty"`
}

// FailedExecution defines model for Execution.
type FailedExecution struct {
	Branch      string     `json:"branch,omitempty"`
	CommitSHA   string     `json:"commit_sha,omitempty"`
	CreatedAt   *Timestamp `json:"created_at,omitempty"`
	Duration    float64    `json:"duration,omitempty"`
	ExecutionID string     `json:"execution_id,omitempty"`

	// FailureExpanded Only present when `include_failure_expanded=true`.
	FailureExpanded  []FailureExpanded `json:"failure_expanded,omitempty"`
	FailureReason    string            `json:"failure_reason,omitempty"`
	Location         string            `json:"location,omitempty"`
	RunID            string            `json:"run_id,omitempty"`
	RunName          string            `json:"run_name,omitempty"`
	RunURL           string            `json:"run_url,omitempty"`
	Tags             map[string]string `json:"tags,omitempty"`
	TestExecutionURL string            `json:"test_execution_url,omitempty"`
	TestID           string            `json:"test_id,omitempty"`
	TestName         string            `json:"test_name,omitempty"`
	TestURL          string            `json:"test_url,omitempty"`
}

// BuildTestExecutionsCount Execution counts by result. `passed` and `failed` are always present;
// `skipped`, `pending`, and `unknown` appear only when non-zero.
type BuildTestExecutionsCount struct {
	Failed  int `json:"failed,omitempty"`
	Passed  int `json:"passed,omitempty"`
	Pending int `json:"pending,omitempty"`
	Skipped int `json:"skipped,omitempty"`
	Unknown int `json:"unknown,omitempty"`
}

// TestLabel defines model for Label.
type TestLabel struct {
	Color string `json:"color,omitempty"`
	Name  string `json:"name,omitempty"`
}

// TestRun defines model for Run.
type TestRun struct {
	Branch    string     `json:"branch,omitempty"`
	BuildID   string     `json:"build_id,omitempty"`
	CommitSHA string     `json:"commit_sha,omitempty"`
	CreatedAt *Timestamp `json:"created_at,omitempty"`
	ID        string     `json:"id,omitempty"`
	Result    string     `json:"result,omitempty"`
	State     string     `json:"state,omitempty"`
	URL       string     `json:"url,omitempty"`
	WebURL    string     `json:"web_url,omitempty"`
}

// TestSuite defines model for Suite.
type TestSuite struct {
	// APIToken Only present when `show_api_token` is requested and permitted.
	APIToken        string `json:"api_token,omitempty"`
	ApplicationName string `json:"application_name,omitempty"`
	Color           string `json:"color,omitempty"`
	DefaultBranch   string `json:"default_branch,omitempty"`
	Emoji           string `json:"emoji,omitempty"`
	GraphQLID       string `json:"graphql_id,omitempty"`
	ID              string `json:"id,omitempty"`
	Name            string `json:"name,omitempty"`

	// OIDCPolicy OIDC policy (YAML string or structured policy statements).
	OIDCPolicy     interface{} `json:"oidc_policy,omitempty"`
	OrganizationID string      `json:"organization_id,omitempty"`
	Slug           string      `json:"slug,omitempty"`
	URL            string      `json:"url,omitempty"`
	WebURL         string      `json:"web_url,omitempty"`
}

// Test defines model for Test.
type Test struct {
	FileName string   `json:"file_name,omitempty"`
	ID       string   `json:"id,omitempty"`
	Labels   []string `json:"labels,omitempty"`
	Location string   `json:"location,omitempty"`
	Name     string   `json:"name,omitempty"`
	Scope    string   `json:"scope,omitempty"`
	URL      string   `json:"url,omitempty"`
	WebURL   string   `json:"web_url,omitempty"`
}
